### ISSUE TITLE
Nose is going out of style

### ISSUE THREAD

**Issue by rhelmot** [angr/angr-dev#100]
`nose` will no longer be supported as of python 3.9. `nose2`, which we have started using in CI, is a little more unweildy to use, and notably does not include an equivalent to `nose.tools.assert_*`. The proposed fix for this is to simply remove all the nose-based asserts and replace them with vanilla asserts, though if anyone wanted to take up the project of converting all our testcases to unittest-style classes, that would be cool as well.

**Comment by twizmwazin** [comment]
I believe we are nearly there in eliminating nose. There are two repos I believe with remaining nose references, claripy and cle.

https://github.com/angr/claripy/pull/261

https://github.com/angr/cle/tree/removeNose_cle
