### ISSUE TITLE
pypy_venv.sh fails on Ubuntu 1804

### ISSUE THREAD

**Issue by jpstotz** [angr/angr-dev#108]
Hi,

I am having problems using the recent version of `pypy_venv.sh` script on Ubuntu 18.04. 

The script fails when executing the command `python3 -m pip install virtualenvwrapper` (this should be https://github.com/angr/angr-dev/blob/master/pypy_venv.sh#L68) 

The error is `Could not find an activated virtualenv (required).` 

I am not sure how this script is supposed to work. Do I have to create and activate a virtualenv before starting it and the script then generates a second pypy based virtualenv?

**Comment by twizmwazin** [comment]
As a workaround, you could probably get by installing PyPy and creating a venv with it normally, and then running setup.sh from that virtualenv or with with the -e flag and then virtualenvwarpper name of that virtualenv.

**Comment by jpstotz** [comment]
@twizmwazin As a workaround I simply commented out that line. My Ubuntu system already has virtualenvwrapper installed via apt.
