### ISSUE TITLE
Call plot_cg(cfg.kb, 'out.png')     call  use demangled_name    for function node names?

### ISSUE THREAD

**Issue by gthaker** [angr/angr-dev#111]
The function callgraph generated by plot_cg()  does not use demanged_names. (demanged_names appear to be available in non-stripped ELF binary files, and possibly for windows PE files w/ accompanying .pdb file.)

Looks like in angr-dev/bingraphvis/bingraphvis/base.py  in VisPipeLine.process()  perhaps this can be handled? (I may have this totally wrong, I just looked around code a bit.)

**Comment by rhelmot** [comment]
bingraphvis is not an angr tool - it is developed by axt [https://github.com/axt/bingraphvis](here).
