### ISSUE TITLE
Daily Status CI

### ISSUE THREAD

**Issue by rhelmot** [angr/angr-dev#13]
Once a day, we should have a script that installs everything, runs all the examples, including the really really long ones, and runs @salls' speed tests and logs the results.

Potentially, if everything passes, the script could also make a release, but that would be a lot of releases. Do we care about constantly pushing these huge new releases? Is that detrimental to the health of the pypi platform?

We also need to figure out where this should be running. I think a cron job on an internal server would be sufficient tbh, but we could look at how to do that with travis/appveyor.

**Comment by zardus** [comment]
I think doing that would be a huge PITA with Travis, and we'd have to deal with the timeouts and so on.
