### ISSUE TITLE
Segmentation fault

### ISSUE THREAD

**Issue by p611148aadsl** [angr/angr-dev#14]
I installed angr-dev.But how to do with segmentation fault when i use it?

![20170225103403](https://cloud.githubusercontent.com/assets/11703999/23327375/fccbac8e-fb45-11e6-9366-492bf0909002.png)

**Comment by rhelmot** [comment]
Please show the output of `dmesg | tail` immediately after the segfault.

**Comment by p611148aadsl** [comment]
here
![20170225104213](https://cloud.githubusercontent.com/assets/11703999/23327430/22bb45ac-fb47-11e6-9d37-e0415ee8f71d.png)

**Comment by rhelmot** [comment]
You waited too long after the segfault. dmesg is a general system log that contains lots of things, including the location of segfaults.

Please run `python solve.py; dmesg | tail` and post the results.

**Comment by p611148aadsl** [comment]
sorry..I'm a new user of angr..
![20170225104636](https://cloud.githubusercontent.com/assets/11703999/23327480/cff9b622-fb47-11e6-82e5-0d4115a24d59.png)

**Comment by rhelmot** [comment]
Are you running in a 32-bit machine? There are some pending issues with installing angr on 32-bit linux. If this is the case, you're almost certainly using a VM, and you should switch to a 64-bit VM.

**Comment by p611148aadsl** [comment]
You are right.I'm using angr in a 32-bit virtual machine.I will try it again in a 64-bit VM.
Thanks you very much!

**Comment by p611148aadsl** [comment]
There is a problem when I try to analyses a binary on mips.
![20170302110157](https://cloud.githubusercontent.com/assets/11703999/23491876/fef6c76a-ff3b-11e6-97f5-cd0b40a1ab64.png)

**Comment by ltfish** [comment]
I've never seen it. Is it still a 32-bit VM?

**Comment by p611148aadsl** [comment]
It is a 64-bit VM.But the binary is on mips.I got it from the filesystem in a router firmware.

**Comment by p611148aadsl** [comment]
Here is the binary.
[webs.zip](https://github.com/angr/angr-dev/files/815788/webs.zip)

**Comment by p611148aadsl** [comment]
I think it is because i tried it on a 64-bit VM but the binary is a 32-bit on mips.There is no problem when i tried this binary on a 32-bit VM.

**Comment by rhelmot** [comment]
so I haven't had time to look at this (and I still don't have time!) but I'm popping in to say that that's not the intended behavior - ideally you should be able to analyze any binary from any platform. Any difference in behavior of angr between platforms is a bug.
