### ISSUE TITLE
Incompatible versions of some packages due to updates in the last three days

### ISSUE THREAD

**Issue by ffhgfv** [angr/angr-dev#164]
Because you updated some packages three days ago, the versions of 'aliment', 'angr', 'angr management', 'clarity', 'cle', 'pyvex', and 'archr' packages are inconsistent, leading to incompatibilities. Although I manually adjusted these packages to version 9.2.18, there are still errors in use. How to solve this problem?

**Comment by rhelmot** [comment]
installing all of those packages in a fresh virtualenv works for me. Are you sure you're not trying to mix dev and pypi versions?

**Comment by mahaloz** [comment]
@ffhgfv are you using the `setup.sh` script? If so, and you still error, could you post the error? My hunch is that it has something to do with setuptools still.
