### ISSUE TITLE
Prefer `angr` repos to external repos?

### ISSUE THREAD

**Issue by zwimer** [angr/angr-dev#167]
In `extremely-simple-setup.py` at https://github.com/angr/angr-dev/blob/0f43373411408bbee56e0ecc74256f65be2e3581/extremely-simple-setup.sh#L51

These repos contain links to things like `https://github.com/salls/angrop.git`; should we instead prefer `https://github.com/angr/angrop.git` and such (if they exist)? That one, like `rex`, just redirects to `angr`'s anyway.

**Comment by zwimer** [comment]
@twizmwazin Thoughts?

**Comment by ltfish** [comment]
We have moved `angrop` to the angr organization, so we should use `https://github.com/angr/angrop.git`. It's the same for rex.
