### ISSUE TITLE
The current cle Git remote source version is 8.20.7.27 instead of the expected 9.2.11.dev0, causing archinfo version errors during installation.

### ISSUE THREAD

**Issue by JohenanLi** [angr/angr-dev#190]
### Description

I encountered an issue during the installation process following the README instructions. The error log indicated that the archinfo version was incorrect due to the cle Git remote source version being https://git@github.com/mborgerson/cle 8.20.7.27 instead of the expected https://git@github.com/angr/cle 9.2.11.dev0.

Error Log:
``
ERROR: Ignored the following versions that require a different python version: 7.8.9.26 Requires-Python <3.0
ERROR: Could not find a version that satisfies the requirement archinfo==9.2.111.dev0 (from angr) (from versions: 0.1, 0.2, 0.3, 4.5.9.9b0, 4.5.9.9, 4.5.9.13, 4.5.9.14, 4.5.10.14, 4.5.10.15, 4.5.11.23, 4.5.12.12, 4.5.12.21, 4.6.2.25, 4.6.3.15, 4.6.5.27, 4.6.6.4, 4.6.6.10, 4.6.6.28, 5.6.8.22, 5.6.10.5, 5.6.12.3, 6.7.1.13, 6.7.3.26, 6.7.4.12, 6.7.6.9, 6.7.7.27, 7.7.9.8, 7.7.9.14, 7.7.12.16, 7.8.2.21, 7.8.6.16, 7.8.7.1, 7.8.8.1, 8.18.10.5, 8.18.10.25, 8.19.2.4, 8.19.4.5, 8.19.7.25, 8.19.10.29, 8.19.10.30, 8.20.1.7, 8.20.5.27, 8.20.6.1, 8.20.6.8, 8.20.7.6, 8.20.7.27, 9.0.4378, 9.0.4446, 9.0.4495, 9.0.4663, 9.0.4885, 9.0.4940, 9.0.5002, 9.0.5034, 9.0.5171, 9.0.5326, 9.0.5327, 9.0.5376, 9.0.5405, 9.0.5450, 9.0.5609, 9.0.5610, 9.0.5739, 9.0.5811, 9.0.5903, 9.0.6136, 9.0.6281, 9.0.6421, 9.0.6488, 9.0.6588, 9.0.6642, 9.0.6790, 9.0.6852, 9.0.6885, 9.0.7293, 9.0.7491, 9.0.7833, 9.0.7912, 9.0.8021, 9.0.8761, 9.0.9031, 9.0.9166, 9.0.9297, 9.0.9355, 9.0.9438, 9.0.9506, 9.0.9572, 9.0.9684, 9.0.9792, 9.0.9947, 9.0.10010, 9.0.10055, 9.0.10072, 9.0.10159, 9.0.10281, 9.0.10339, 9.0.10409, 9.0.10534, 9.0.10576, 9.0.10651, 9.0.10689, 9.0.10730, 9.1.10913, 9.1.11508, 9.1.11611, 9.1.11752, 9.1.12332, 9.2.1, 9.2.2, 9.2.3, 9.2.4, 9.2.5, 9.2.6, 9.2.7, 9.2.8, 9.2.9, 9.2.10, 9.2.11, 9.2.12, 9.2.13, 9.2.14, 9.2.15, 9.2.16, 9.2.17, 9.2.18, 9.2.19, 9.2.20, 9.2.21, 9.2.22, 9.2.23, 9.2.24, 9.2.25, 9.2.26, 9.2.27, 9.2.28, 9.2.29, 9.2.30, 9.2.31, 9.2.32, 9.2.33, 9.2.34, 9.2.35, 9.2.36, 9.2.37, 9.2.38, 9.2.39, 9.2.40, 9.2.41, 9.2.42, 9.2.43, 9.2.44, 9.2.45, 9.2.46, 9.2.47, 9.2.48, 9.2.49, 9.2.50, 9.2.51, 9.2.52, 9.2.53, 9.2.54, 9.2.55, 9.2.56, 9.2.57, 9.2.58, 9.2.59, 9.2.60, 9.2.61, 9.2.62, 9.2.63, 9.2.64, 9.2.65, 9.2.66, 9.2.67, 9.2.68, 9.2.69, 9.2.70, 9.2.71, 9.2.72, 9.2.73, 9.2.74, 9.2.75, 9.2.76, 9.2.77, 9.2.78, 9.2.79, 9.2.80, 9.2.81, 9.2.82, 9.2.83, 9.2.84, 9.2.85, 9.2.86, 9.2.87, 9.2.88, 9.2.89, 9.2.90, 9.2.91, 9.2.92, 9.2.93, 9.2.94, 9.2.95, 9.2.96, 9.2.97, 9.2.98, 9.2.99, 9.2.100, 9.2.101, 9.2.102, 9.2.103, 9.2.104, 9.2.105, 9.2.106, 9.2.107, 9.2.108, 9.2.109, 9.2.110)
ERROR: No matching distribution found for archinfo==9.2.111.dev0
```

### Steps to reproduce the bug

1. git clone angr-dev
2. ./setup.sh -i -e angr 

### Environment

_No response_

### Additional context

_No response_

**Comment by twizmwazin** [comment]
cle should be cloned from angr/cle, not mborgerson/cle. This issue can happen when git clone fails randomly, which is a known issue. Try manually cloning the cle repo and rerunning the setup.sh script.

**Comment by twizmwazin** [comment]
Closing as solved, let us know if you need additional help.
