### ISSUE TITLE
cle.backends.elf.ELF AttributeError

### ISSUE THREAD

**Issue by nimrodpar** [angr/angr-dev#24]
`elf = cle.backends.elf.ELF('/bin/true')`

gives:
```
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/home/user/workspace/angr-dev/cle/cle/backends/elf.py", line 214, in __init__
    self.__register_segments()
  File "/home/user/workspace/angr-dev/cle/cle/backends/elf.py", line 397, in __register_segments
    self._load_segment(seg_readelf)
  File "/home/user/workspace/angr-dev/cle/cle/backends/elf.py", line 411, in _load_segment
    self._load_segment_memory(seg)
  File "/home/user/workspace/angr-dev/cle/cle/backends/elf.py", line 425, in _load_segment_memory
    if ph.p_align & (self.loader.page_size - 1) != 0:
AttributeError: 'NoneType' object has no attribute 'page_size'
```
But `elf = cle.backends.elf.ELF('/bin/true', loader=cle.Loader("/bin/true"))` works fine.

(on Ubuntu 16.10 64bit)

**Comment by ltfish** [comment]
Obviously the `loader` argument is essential here. I'm not sure if this is something that needs a fix. @rhelmot ?

**Comment by nimrodpar** [comment]
Right, i switched from using the pip release of angr to angr-dev and saw this discrepancy..maybe add it as a non-optional arg?

**Comment by ltfish** [comment]
`loader` is a new argument introduced by the latest CLE refactor. My proposed fix is to either raise an exception if `loader` is None, or just initialize a default loader (see [here](https://github.com/angr/cle/blob/master/cle/backends/__init__.py#L435)). I prefer the previous choice.

Actually, @subwire is the right one to ask for this question. @subwire !

**Comment by ltfish** [comment]
> maybe add it as a non-optional arg
It has to be a keyword argument to keep backward compatibility with other projects.

**Comment by rhelmot** [comment]
Hi, I just saw this! Yes, you need a loader instance to load things. You don't necessarily need to have everything in the loader's address space though - you can use `loader.load_object("/bin/true")` to get the same result. You can specify `backend=cle.backends.elf.ELF` if you like to force that backend, though it will be the default.
