### ISSUE TITLE
Dependency-Problem through angrop

### ISSUE THREAD

**Issue by AndyXan** [angr/angr-dev#29]
Hello,

when installing angr for development, with ./setup.sh -i -e repo, angrop is automatically cloned and installed. The setup.py file froom angrop has as its dependency angr itself, which gets installed via pip install angr - getting the lattest pip version from angr overriding any changes made to the cloned angr repository itself.

Would be good to get angrop as "optional" or angr be listed as setup_requires instead of install_requires where its getting installed automatically.

Greetings,
Andy

**Comment by zardus** [comment]
That's weird, and `setup.sh` should explicitly put the angr editable install before anything depending on it in the list of packages, so this shouldn't happen.

Just to confirm: your aim is to install everything in a virtualenv called `repo`, right? That's what `setup.sh -i -e repo` will do...

**Comment by AndyXan** [comment]
Hmm, that's odd. Yes basically what we're doing is clone our forked repositories and call setup.sh -i -e afterwards. What happened is that both, angr in editable mode has been installed as well as angr from the pip repo itself, e.g. pip freeze | grep angr --> angr 6.7.9.6, /some-repo-path -e angr. When importing angr in ipython the pip angr repo was imported.

So i checked from where pip angr would come from and the only project where its listed as dependency was angrop, thus assuming it has to be the case but i might be wrong. I'm going to verify this behaviour tomorrow with a detailed description of the steps

**Comment by AndyXan** [comment]
Sry took me some time to again test it:

So after a complete fresh deployment, e.g. clone angr-dev, clone forked cle, pyvex, angr and idalink as their respective angr-dev install script name 'angr, cle, idalink, pyvex' directory with calling setup.sh -i -e 'sit-angr' the result is the following:

```
angr==6.7.6.9
angr-only-z3-custom==9002
-e git+https://git:@github.com/salls/angrop@0b675178d76dfa83ba558052623d810b9086fdf0#egg=angrop 
... lots of editable installs
-e git+https://forked-angr-repo/angr@bdaf61e27b2eb45833c0b5b3ff1a89c215989e16#egg=sit_angr
```

I assume it comes from the hardcoded dependency from angrop setup.py. Both, angr 6.7.6.9 from pip and the editable angr from the custom repo are installed, however when using ipython import angr - the repo angr gets the priority.

When removing angr 6.7.6.9 from the setup requires, this does not happen. I'm no expert in python packaging, so, i could also be entirely wrong :)

**Comment by rhelmot** [comment]
I don't see a requirement on a version of `angr` in any repository, especially angrop: https://github.com/salls/angrop/blob/master/setup.py. Can you explain what you removed?

The solution is probably to just bump the version number of your fork to 6.7.6.9, regardless.

**Comment by AndyXan** [comment]
I'm going to close this for now. Seems like there might be something wrong from our side. If something comes up, i'll let you know.
