### ISSUE TITLE
Installing angr-dev using ./setup.sh errors out

### ISSUE THREAD

**Issue by pragyansmita** [angr/angr-dev#32]
We are trying to install angr-dev version following the instructions in the install guide at https://docs.angr.io/INSTALL.html

We follow the steps in the section titled "Development Install". However, we are seeing the following errors:

ubuntu@ubuntu:~/code/angr-dev$ git clone https://github.com/angr/angr-dev.git
Cloning into 'angr-dev'...
remote: Counting objects: 949, done.
remote: Compressing objects: 100% (6/6), done.
remote: Total 949 (delta 1), reused 4 (delta 1), pack-reused 942
Receiving objects: 100% (949/949), 160.01 KiB | 0 bytes/s, done.
Resolving deltas: 100% (581/581), done.
Checking connectivity... done.

ubuntu@ubuntu:~/code/angr-dev$ cd angr-dev/

ubuntu@ubuntu:~/code/angr-dev/angr-dev$ mkvirtualenv angr
New python executable in /home/ubuntu/co/virtual_env/angr/bin/python
Installing setuptools, pip, wheel...done.

(angr) ubuntu@ubuntu:~/code/angr-dev/angr-dev$ ls
admin  Dockerfile  git_all.bat  git_all.sh  LICENSE  pylintrc  pypy_venv.sh  README.md  setup.bat  setup.sh  standard_logging.py  tests

(angr) ubuntu@ubuntu:~/code/angr-dev/angr-dev$ ./setup.sh 
[+] 13:51:56 Checking dependencies...
dpkg: no packages found matching virtualenvwrapper
dpkg: no packages found matching python-pip
dpkg: no packages found matching libxml2-dev
dpkg: no packages found matching libxslt1-dev
dpkg: no packages found matching libreadline-dev
dpkg: no packages found matching debootstrap
dpkg: no packages found matching debian-archive-keyring
dpkg: no packages found matching libglib2.0-dev
dpkg: no packages found matching libpixman-1-dev
dpkg: no packages found matching graphviz-dev
dpkg: no packages found matching nasm
dpkg: no packages found matching libc6:i386
dpkg: no packages found matching libgcc1:i386
dpkg: no packages found matching libstdc++6:i386
dpkg: no packages found matching libtinfo5:i386
dpkg: no packages found matching zlib1g:i386
[!!] 13:51:56 Please install the following packages: virtualenvwrapper python-pip python2.7-dev build-essential libxml2-dev libxslt1-dev git libffi-dev cmake libreadline-dev libtool debootstrap debian-archive-keyring libglib2.0-dev libpixman-1-dev libqt4-dev graphviz-dev binutils-multiarch nasm libc6:i386 libgcc1:i386 libstdc++6:i386 libtinfo5:i386 zlib1g:i386
[+] Checking dependencies...
[!!] Please install the following packages: virtualenvwrapper python-pip python2.7-dev build-essential libxml2-dev libxslt1-dev git libffi-dev cmake libreadline-dev libtool debootstrap debian-archive-keyring libglib2.0-dev libpixman-1-dev libqt4-dev graphviz-dev binutils-multiarch nasm libc6:i386 libgcc1:i386 libstdc++6:i386 libtinfo5:i386 zlib1g:i386

(angr) ubuntu@ubuntu:~/code/angr-dev/angr-dev$ pip install virtualenvwrapper python-pip python2.7-dev build-essential libxml2-dev libxslt1-dev git libffi-dev cmake libreadline-dev libtool debootstrap debian-archive-keyring libglib2.0-dev libpixman-1-dev libqt4-dev graphviz-dev binutils-multiarch nasm libc6:i386 libgcc1:i386 libstdc++6:i386 libtinfo5:i386 zlib1g:i386
Invalid requirement: 'libc6:i386'
Traceback (most recent call last):
  File "/home/ubuntu/co/virtual_env/angr/local/lib/python2.7/site-packages/pip/req/req_install.py", line 82, in __init__
    req = Requirement(req)
  File "/home/ubuntu/co/virtual_env/angr/local/lib/python2.7/site-packages/pip/_vendor/packaging/requirements.py", line 96, in __init__
    requirement_string[e.loc:e.loc + 8]))
InvalidRequirement: Invalid requirement, parse error at "':i386'"

(angr) ubuntu@ubuntu:~/code/angr-dev/angr-dev$ sudo pip install virtualenvwrapper python-pip python2.7-dev build-essential libxml2-dev libxslt1-dev git libffi-dev cmake libreadline-dev libtool debootstrap debian-archive-keyring libglib2.0-dev libpixman-1-dev libqt4-dev graphviz-dev binutils-multiarch nasm libc6:i386 libgcc1:i386 libstdc++6:i386 libtinfo5:i386 zlib1g:i386
The directory '/home/ubuntu/.cache/pip/http' or its parent directory is not owned by the current user and the cache has been disabled. Please check the permissions and owner of that directory. If executing pip with sudo, you may want sudo's -H flag.
The directory '/home/ubuntu/.cache/pip' or its parent directory is not owned by the current user and caching wheels has been disabled. check the permissions and owner of that directory. If executing pip with sudo, you may want sudo's -H flag.
Invalid requirement: 'libc6:i386'
Traceback (most recent call last):
  File "/usr/local/lib/python2.7/dist-packages/pip/req/req_install.py", line 82, in __init__
    req = Requirement(req)
  File "/usr/local/lib/python2.7/dist-packages/pip/_vendor/packaging/requirements.py", line 96, in __init__
    requirement_string[e.loc:e.loc + 8]))
InvalidRequirement: Invalid requirement, parse error at "':i386'"

**Comment by zardus** [comment]
A few things:

1. Please don't install angr (and dependencies) outside of a virtualenv. We have no idea what'll happen. If you're typing `sudo pip` while installing angr, you're doing something wrong :-)
2. Your last command (that errored out) should be `sudo apt-get` not `sudo pip`. Those are debian package dependencies that you need, not python dependencies.
3. `setup.sh` can do all the dependency installation for you if you do `setup.sh -i`.

Also, it might be easier to use the docker image to get started `docker run -it angr/angr` will get you a ready-to-use angr.
