### ISSUE TITLE
Officially support making a development install on macOS

### ISSUE THREAD

**Issue by ltfish** [angr/angr-dev#34]
The primary issue is that `libunicorn.dylib` cannot load `libpyvex.dylib` on macOS. Possible solutions are:

- Setting `rpath` to `$ORIGIN`. Thanks @dfraze for this suggestion (if it works).
- Running `install_name_tool` on libunicorn.dylib as suggested in [this issue](https://github.com/angr/angr/issues/234).

**Comment by Usibre** [comment]
Sidenote: the setup script on this repo doesn't work on the default bash on a mac as they are still running bash 3.x and the script uses associative arrays (added in bash 4).
