### ISSUE TITLE
setup.sh installs incompatible PyPy binary for Debian stable

### ISSUE THREAD

**Issue by carter-yagemann** [angr/angr-dev#58]
**Problem:**

On stable Debian (currently Stretch), when `setup.py` is told to use PyPy (`-p` or `-P` flag), `pypy_venv.sh` tries to fetch the latest official PyPy release, which is currently `pypy3-v6.0.0-linux64`. Unfortunately, the PyPy binary in this release fails to link against `libssl.so.1.0.0`, meaning `pip` cannot use SSL/TLS, ultimately causing the setup to fail.

**Possible Solutions:**

1) Fetch portable PyPy instead.

The official PyPy [install documentation](http://pypy.org/download.html) mentions an [unofficial portable build](https://github.com/squeaky-pl/portable-pypy#portable-pypy-distribution-for-linux) of PyPy. Since this version provides its own `libssl` library, it avoids the above issue. I've tested this solution and it works.

2) Wait for Debian to offer a PyPy3 package.

Debian has a `pypy` package, but it's currently PyPy 5.6 and implements Python 2.x, not 3.x. The upcoming stable (Buster) will package PyPy 6.0, but it's unclear if this binary is going to support 2.x and 3.x, or just 2.x. There's currently an [open ticket](https://bugs.debian.org/cgi-bin/bugreport.cgi?bug=825970) for this issue.

3) Symlink `libssl` to hotfix the issue.

Debian Stretch has `libssl` packages that provide `libssl.so.1.0.2` and `libssl.so.1.1`. Symlinking `libssl.so.1.0.0` to one of these will probably fix the issue, but this is an ad-hoc fix and there may be other linking errors beyond `libssl`.

**Comment by rhelmot** [comment]
I’m shocked that pypy is linking against a specific revsision version of
libssl - this should probably be opened as a pypy bug. Option 3 is my
favorite for this reason.

I don’t think there’s much of a need to do anything on the angr side,
unless you want to contribute a new install flag for option 2. I would
prefer the -p flag to install the bleeding edge version.

**Comment by carter-yagemann** [comment]
Regarding option 3, the closest `libssl` version provided by Debian Stretch is `1.0.2`, but if I symlink it, `import ssl` produces the following error:

    ImportError: /usr/lib/x86_64-linux-gnu/libssl.so.1.0.0: version `OPENSSL_1.0.1' not found (required by /pypy3-v6.0.0-linux64/lib_pypy/_pypy_openssl.pypy3-60-x86_64-linux-gnu.so)

I agree that this isn't an `angr` bug, so I'll close this issue and open one with the PyPy devs.

Thanks.
