### ISSUE TITLE
Docker not building again

### ISSUE THREAD

**Issue by bannsec** [angr/angr-dev#68]
This time i'm not sure why. I can build it just fine, but it's been 10 days since the latest autobuild on angr/angr.

Maybe something to do with this: https://success.docker.com/article/i-have-issues-triggering-autobuilds

**Comment by rhelmot** [comment]
The answer was actually that I accidentally triggered a partial upgrade of some legacy configuration a week ago while setting up a new image and everything started silently failing. I believe it should be fixed now...
