### ISSUE TITLE
Arch linux QT4 depency dropped

### ISSUE THREAD

**Issue by balbassam** [angr/angr-dev#78]
It appears as though in the `setup.sh` script qt4 is being pulled in as a dependency with the `-i` option on arch linux. Arch [has dropped qt4 support officially](https://lists.archlinux.org/pipermail/arch-dev-public/2019-April/029560.html) but it is available in the [AUR](https://aur.archlinux.org/packages/qt4).
As qt4 cannot be pulled in from the official repos, the setup fails.

Looking at the source it seems as though it qt4 is only needed for [angr-management](https://github.com/angr/angr-management).

**Comment by ltfish** [comment]
angr management relies on Qt5, not Qt4 anymore. Can you please update setup.sh for Arch?

**Comment by balbassam** [comment]
Tested and created pull request that works on Arch.

One thing to note is that there is a reference to QT4
[remaining](https://github.com/angr/angr-management/blob/3970f3dd7bd843a784c16253e3349c788d336ef8/angrmanagement/ui/widgets/qipython_widget.py#L15-L26). I'm not sure if that matters though.

**Comment by rhelmot** [comment]
In all likelyhood those interfaces still exist for backwards compatibility and will do the right thing even though we're using qt5. Wouldn't hurt to see if there's something better to do though. Thanks for the patch!
