### ISSUE TITLE
setup.sh does not install angr-targets

### ISSUE THREAD

**Issue by saullocarvalho** [angr/angr-dev#80]
The module is used on `angr/angr/engines/concrete.py` and some angr tests. Is there a reason for this?

AppVeyor tests raise errors related to missing avatar2, which is a dependency of angr-targets.

**Comment by rhelmot** [comment]
Setup.sh doesn’t need to install angr-targets. If we installed everything
necessary to run all tests with setup.sh, users would complain about how
long install took. For example, we don’t install cvc4-solver, which is used
in some claripy tests.

You should make the avatar2 import optional (except ImportError, and then
raise SkipTest if it’s not imported). I don’t think it can be realistically
installed on windows.

**Comment by saullocarvalho** [comment]
Thanks for the explanation.
I've just submitted two PRs to handle those cases.
