### ISSUE TITLE
Failing `clone_repo` do not display what went wrong

### ISSUE THREAD

**Issue by Pamplemousse** [angr/angr-dev#83]
During the `setup.sh`, [in the `clone_repo` function](https://github.com/angr/angr-dev/blob/master/setup.sh#L355-L358), the following code is hit if a repo fails for whatever reason:

```bash
error "Failed to clone $NAME. Error was:"
cat $CLONE_LOG
rm -f $CLONE_LOG
return 1
```

However, the [`error` function ending with an `exit 1`](https://github.com/angr/angr-dev/blob/master/setup.sh#L170-L180), the script exits before the display of the log ever happens (because the three lines after the `error` call are never executed).

Note that for the same reason, the `/tmp/clone-...` files are not cleaned up.

**Comment by rhelmot** [comment]
could this just be fixed by `set +e` and `set -e` around the clone loop?
