### ISSUE TITLE
Cannot install in Windows, pyvex error

### ISSUE THREAD

**Issue by Pl0414141** [angr/angr-dev#88]
C:\Users\sym\Desktop\angr-dev-master\angr-dev-master>setup.bat

pip fails in pyvex installation
...
C:\Users\sym\Desktop\angr-dev-master\angr-dev-master>pip install -e .\pyvex   || goto :error
Obtaining file:///C:/Users/sym/Desktop/angr-dev-master/angr-dev-master/pyvex
Requirement already satisfied: pycparser in c:\python35\lib\site-packages (from pyvex==8.19.7.25) (2.18)
Requirement already satisfied: cffi>=1.0.3 in c:\python35\lib\site-packages (from pyvex==8.19.7.25) (1.11.2)
Requirement already satisfied: archinfo==8.19.7.25 in c:\users\sym\desktop\angr-dev-master\angr-dev-master\archinfo (from pyvex==8.19.7.25) (8.19.7.25)
Requirement already satisfied: bitstring in c:\python35\lib\site-packages (from pyvex==8.19.7.25) (3.1.6)
Requirement already satisfied: future in c:\python35\lib\site-packages (from pyvex==8.19.7.25) (0.16.0)
Installing collected packages: pyvex
  Found existing installation: pyvex 8.19.7.25
    Uninstalling pyvex-8.19.7.25:
      Successfully uninstalled pyvex-8.19.7.25
  Running setup.py develop for pyvex
    ERROR: Command errored out with exit status 1:
     command: 'c:\python35\python3.exe' -c 'import sys, setuptools, tokenize; sys.argv[0] = '"'"'C:\\Users\\sym\\Desktop\\angr-dev-master\\angr-dev-master\\pyvex\\setup.py'"'"'; __file__='"'"'C:\\Users\\sym\\Desktop\\angr-dev-master\\angr-dev-master\\pyvex\\setup.py'"'"';f=getattr(tokenize, '"'"'open'"'"', open)(__file__);code=f.read().replace('"'"'\r\n'"'"', '"'"'\n'"'"');f.close();exec(compile(code, __file__, '"'"'exec'"'"'))' develop --no-deps
         cwd: C:\Users\sym\Desktop\angr-dev-master\angr-dev-master\pyvex\
    Complete output (3 lines):
    running develop
    Building libVEX
    error: Unable to build libVEX.
    ----------------------------------------
  Rolling back uninstall of pyvex
  Moving to c:\python35\lib\site-packages\pyvex-8.19.7.25.dist-info\
   from c:\python35\lib\site-packages\~yvex-8.19.7.25.dist-info
  Moving to c:\python35\lib\site-packages\pyvex\
   from c:\python35\lib\site-packages\~yvex
ERROR: Command errored out with exit status 1: 'c:\python35\python3.exe' -c 'import sys, setuptools, tokenize; sys.argv[0] = '"'"'C:\\Users\\sym\\Desktop\\angr-dev-master\\angr-dev-master\\pyvex\\setup.py'"'"'; __file__='"'"'C:\\Users\\sym\\Desktop\\angr-dev-master\\angr-dev-master\\pyvex\\setup.py'"'"';f=getattr(tokenize, '"'"'open'"'"', open)(__file__);code=f.read().replace('"'"'\r\n'"'"', '"'"'\n'"'"');f.close();exec(compile(code, __file__, '"'"'exec'"'"'))' develop --no-deps Check the logs for full command output.

C:\Users\sym\Desktop\angr-dev-master\angr-dev-master>echo "Development install failed!"
"Development install failed!"

**Windows version: 10, 1903
Python version: 3.5
Git: 2.23.0**

**Comment by rhelmot** [comment]
Are you running this in the visual studio developer command prompt?

**Comment by Pl0414141** [comment]
@rhelmot Yes, "Developer Command Prompt for VS 2019", now appears another error with the installation of angr:

Installing collected packages: angr
  Found existing installation: angr 8.19.7.25
    Uninstalling angr-8.19.7.25:
      Successfully uninstalled angr-8.19.7.25
  Running setup.py develop for angr
    ERROR: Command errored out with exit status 1:
     command: 'c:\python35\python3.exe' -c 'import sys, setuptools, tokenize; sys.argv[0] = '"'"'C:\\Users\\sym\\Desktop\\angr-dev-master\\angr-dev-master\\angr\\setup.py'"'"'; __file__='"'"'C:\\Users\\sym\\Desktop\\angr-dev-master\\angr-dev-master\\angr\\setup.py'"'"';f=getattr(tokenize, '"'"'open'"'"', open)(__file__);code=f.read().replace('"'"'\r\n'"'"', '"'"'\n'"'"');f.close();exec(compile(code, __file__, '"'"'exec'"'"'))' develop --no-deps
         cwd: C:\Users\sym\Desktop\angr-dev-master\angr-dev-master\angr\
    Complete output (3 lines):
    running develop
    Building angr_native
    error: cannot load library c:\users\sym\desktop\angr-dev-master\angr-dev-master\pyvex\pyvex\lib\pyvex.dll: error 0xc1
    ----------------------------------------
  Rolling back uninstall of angr
  Moving to c:\python35\lib\site-packages\angr-8.19.7.25.dist-info\
   from c:\python35\lib\site-packages\~ngr-8.19.7.25.dist-info
  Moving to c:\python35\lib\site-packages\angr\
   from c:\python35\lib\site-packages\~ngr
ERROR: Command errored out with exit status 1: 'c:\python35\python3.exe' -c 'import sys, setuptools, tokenize; sys.argv[0] = '"'"'C:\\Users\\sym\\Desktop\\angr-dev-master\\angr-dev-master\\angr\\setup.py'"'"'; __file__='"'"'C:\\Users\\sym\\Desktop\\angr-dev-master\\angr-dev-master\\angr\\setup.py'"'"';f=getattr(tokenize, '"'"'open'"'"', open)(__file__);code=f.read().replace('"'"'\r\n'"'"', '"'"'\n'"'"');f.close();exec(compile(code, __file__, '"'"'exec'"'"'))' develop --no-deps Check the logs for full command output.

C:\Users\sym\Desktop\angr-dev-master\angr-dev-master>echo "Development install failed!"
"Development install failed!"

**Comment by rhelmot** [comment]
That error makes it look like you are using a 32 bit python interpreter but
you have built pyvex with the 64 bit compiler or vice versa.

**Comment by Pl0414141** [comment]
Fixed using "x86_x64 Native Tools VS 2019"

Thanks
